import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Camera,ChevronRight,Sparkles,Users,ScanLine,Share2,History,Heart,LockKeyhole,X,FileDown}from'lucide-react';
import{buildLongReport,downloadPalmPDF}from'./report.js';
import'./styles.css';
const ARCHETYPES=[
{name:'THE EXPLORER',tag:'Libre • Curieux • Adaptable',intro:'Tu avances par curiosité. Les nouvelles idées, les personnes et les expériences inattendues alimentent ton énergie.',power:'Transformer l’inconnu en terrain de jeu.',strength:'Adaptation',growth:'Garder un cap quand la nouveauté retombe.',potential:'Tu progresses vite quand liberté et objectif clair se rencontrent.',quote:'Tu grandis chaque fois que tu oses aller voir plus loin.'},
{name:'THE STRATEGIST',tag:'Lucide • Calme • Visionnaire',intro:'Tu observes vite, relies les informations et cherches naturellement le meilleur angle avant d’agir.',power:'Voir les connexions avant les autres.',strength:'Vision',growth:'Agir avant d’avoir 100 % des réponses.',potential:'Ton potentiel explose quand tu transformes une analyse juste en action simple.',quote:'Tu ne cherches pas à aller plus vite. Tu cherches à voir plus loin.'},
{name:'THE CONNECTOR',tag:'Social • Intuitif • Magnétique',intro:'Tu captes rapidement les ambiances et les personnes. Tu sais créer du lien sans chercher à être au centre.',power:'Créer une connexion en quelques instants.',strength:'Empathie',growth:'Ne pas absorber toutes les émotions autour de toi.',potential:'Ton impact augmente lorsque tu assumes davantage ta propre voix.',quote:'Ta force n’est pas de parler plus fort, mais de créer le bon lien.'},
{name:'THE CREATOR',tag:'Original • Intuitif • Expressif',intro:'Ton esprit produit facilement des idées et des façons différentes de regarder les choses.',power:'Voir une possibilité là où les autres voient une limite.',strength:'Créativité',growth:'Finir une idée avant de partir sur la suivante.',potential:'Avec un peu de structure, ton imagination devient un vrai avantage.',quote:'Tu ne vois pas seulement ce qui existe. Tu vois ce qui pourrait exister.'},
{name:'THE LEADER',tag:'Direct • Énergique • Décisif',intro:'Quand un groupe hésite, tu as tendance à créer du mouvement et à faire avancer les choses.',power:'Déclencher l’action quand les autres attendent.',strength:'Décision',growth:'Laisser de la place aux rythmes différents du tien.',potential:'Ton leadership devient puissant lorsqu’il donne envie plutôt qu’il n’impose.',quote:'Tu n’attends pas toujours le moment parfait. Tu crées le moment.'},
{name:'THE GUARDIAN',tag:'Fiable • Loyal • Protecteur',intro:'Tu accordes beaucoup de valeur à la confiance et aux personnes qui comptent vraiment.',power:'Créer un sentiment de sécurité autour de toi.',strength:'Loyauté',growth:'Oser te choisir toi aussi.',potential:'Ta constance est une force rare lorsqu’elle ne devient pas une obligation.',quote:'Ta présence rassure plus que tu ne l’imagines.'}];
const phases=[['Acquisition biométrique','Stabilisation de l’image et isolation de la paume'],['Cartographie palmaire','Repérage de 21 points de référence'],['Analyse morphologique','Mesure des proportions et zones dominantes'],['Détection des patterns','Comparaison des structures et contrastes'],['Modélisation du profil','Pondération des traits dominants'],['Vérification croisée','Contrôle de cohérence du profil'],['Signature PALM','Génération de ton identité']];
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function buildProfile(seed){const p=ARCHETYPES[seed%ARCHETYPES.length];return{id:Date.now(),seed,name:'Profil '+(Date.now()%1000),profile:p,scores:[72+seed%23,67+(seed>>3)%28,70+(seed>>6)%25]}}
function loadHands(){return new Promise((resolve,reject)=>{if(window.Hands)return resolve(window.Hands);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js';s.crossOrigin='anonymous';s.onload=()=>window.Hands?resolve(window.Hands):reject(new Error('Hands unavailable'));s.onerror=reject;document.head.appendChild(s)})}
function App(){
 const[screen,setScreen]=useState('home'),[progress,setProgress]=useState(0),[current,setCurrent]=useState(null),[unlocked,setUnlocked]=useState(localStorage.getItem('palm_unlocked')==='1'),[history,setHistory]=useState(()=>JSON.parse(localStorage.getItem('palm_history')||'[]')),[captured,setCaptured]=useState(null),[guide,setGuide]=useState('Approche ta main'),[cameraError,setCameraError]=useState('');
 const videoRef=useRef(),streamRef=useRef(),handsRef=useRef(),rafRef=useRef(),stableRef=useRef(0),capturedRef=useRef(false);
 const stopCamera=()=>{cancelAnimationFrame(rafRef.current);streamRef.current?.getTracks()?.forEach(t=>t.stop());streamRef.current=null;handsRef.current?.close?.();handsRef.current=null};
 const startCamera=async()=>{stopCamera();setCaptured(null);capturedRef.current=false;setCameraError('');setGuide('Montre ta paume');setScreen('live');stableRef.current=0;try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1280}},audio:false});streamRef.current=stream;await new Promise(r=>setTimeout(r,80));if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}const HandsCtor=await loadHands();const hands=new HandsCtor({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});hands.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.6,minTrackingConfidence:.55});hands.onResults(onHandResults);handsRef.current=hands;const loop=async()=>{if(!handsRef.current||!videoRef.current||capturedRef.current)return;try{await handsRef.current.send({image:videoRef.current})}catch{}rafRef.current=requestAnimationFrame(loop)};loop()}catch(e){setCameraError('Autorise l’accès à la caméra puis réessaie.')}};
 const onHandResults=res=>{if(capturedRef.current)return;const lm=res.multiHandLandmarks?.[0];if(!lm){stableRef.current=0;setGuide('Montre toute ta main');return}const xs=lm.map(p=>p.x),ys=lm.map(p=>p.y),w=Math.max(...xs)-Math.min(...xs),h=Math.max(...ys)-Math.min(...ys),size=Math.max(w,h),cx=(Math.max(...xs)+Math.min(...xs))/2,cy=(Math.max(...ys)+Math.min(...ys))/2;if(size<.48){stableRef.current=0;setGuide('Approche ta main');return}if(size>.82){stableRef.current=0;setGuide('Éloigne un peu ta main');return}if(Math.abs(cx-.5)>.18||Math.abs(cy-.5)>.2){stableRef.current=0;setGuide('Centre ta main');return}stableRef.current+=1;setGuide(stableRef.current>6?'Parfait… ne bouge plus':'Position parfaite');if(stableRef.current>12)captureFrame()};
 const captureFrame=()=>{if(!videoRef.current||capturedRef.current)return;capturedRef.current=true;const v=videoRef.current,c=document.createElement('canvas');c.width=v.videoWidth||720;c.height=v.videoHeight||960;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.82);setCaptured(data);setCurrent(buildProfile(hash(data.slice(-14000))));stopCamera();setProgress(1);setScreen('scan')};
 useEffect(()=>()=>stopCamera(),[]);useEffect(()=>{if(screen!=='scan')return;const t=setInterval(()=>setProgress(p=>Math.min(100,p+1)),105);return()=>clearInterval(t)},[screen]);useEffect(()=>{if(screen==='scan'&&progress>=100){const t=setTimeout(()=>{setHistory(h=>{const next=[...h,{...current,name:'Profil '+(h.length+1)}].slice(-20);localStorage.setItem('palm_history',JSON.stringify(next));return next});setScreen('result')},900);return()=>clearTimeout(t)}},[progress,screen]);
 const phase=phases[Math.min(phases.length-1,Math.floor(progress/(100/phases.length)))];const unlock=()=>{setUnlocked(true);localStorage.setItem('palm_unlocked','1')};const reset=()=>{stopCamera();setCaptured(null);setCurrent(null);setProgress(0);setScreen('home')};const openHistory=()=>setScreen('history');const compare=()=>setScreen('compat');const pair=history.slice(-2),compat=pair.length===2?74+((pair[0].seed^pair[1].seed)%23):0;const longReport=current?buildLongReport(current):[];
 return <main className="app"><header><div className="brand"><i></i>PALM</div><button className="ghost" onClick={openHistory}><History size={17}/></button></header>
 {screen==='home'&&<section className="hero"><div className="eyebrow"><Sparkles size={14}/> SOCIAL PERSONALITY SCAN</div><h1>Ta main.<br/><span>Ton profil.</span></h1><p>Présente ta paume à la caméra. PALM la détecte, ajuste la distance et lance le scan automatiquement.</p><div className="handOrb"><div className="palm">✋</div><div className="orbit o1"></div><div className="orbit o2"></div></div><button className="primary" onClick={startCamera}><Camera size={20}/> OUVRIR LE SCANNER <ChevronRight/></button><button className="secondary" onClick={openHistory}><Users size={18}/> Mes profils</button><small>Aucune photo à prendre • scan automatique</small></section>}
 {screen==='live'&&<section><div className="eyebrow"><ScanLine size={14}/> DÉTECTION LIVE</div><h2>Présente ta paume</h2><p>Le scan démarre automatiquement lorsque la position est parfaite.</p><div className="camera liveCamera"><video ref={videoRef} playsInline muted/><div className="liveShade"></div><div className="guidePalm">✋</div><div className={'guideText '+(guide.includes('Parfait')?'ok':'')}>{guide}</div><div className="distanceRing"></div><span className="corner c1"></span><span className="corner c2"></span><span className="corner c3"></span><span className="corner c4"></span></div>{cameraError&&<div className="cameraError">{cameraError}</div>}<button className="secondary" onClick={reset}><X size={18}/> Annuler</button></section>}
 {screen==='scan'&&<section className="analysisScreen"><div className="eyebrow"><ScanLine size={14}/> ANALYSE PALM</div><h2>Lecture approfondie</h2><p className="analysisLead">Garde quelques secondes : ton profil est en cours de construction.</p><div className="camera scanning deepScan"><img src={captured}/><div className="grid"></div><div className="scanline"></div><div className="target"></div><div className="analysisNodes">{[1,2,3,4,5,6,7,8,9].map(n=><i key={n} style={{left:(15+(n*17)%70)+'%',top:(12+(n*23)%72)+'%'}}></i>)}</div><div className="analysisHud"><span>LANDMARKS 21/21</span><span>CONFIDENCE {(92+Math.floor(progress/15))}%</span></div></div><div className="phaseBox"><div className="phaseTop"><span>0{Math.min(7,Math.floor(progress/(100/7))+1)} / 07</span><strong>{phase[0]}</strong><b>{progress}%</b></div><p>{phase[1]}</p><div className="progress"><b style={{width:progress+'%'}}></b></div></div><div className="phaseList">{phases.map((p,i)=>{const active=i===Math.min(6,Math.floor(progress/(100/7))),done=i<Math.floor(progress/(100/7));return <div className={(active?'active ':'')+(done?'done':'')} key={p[0]}><i>{done?'✓':active?'•':'○'}</i><span>{p[0]}</span></div>})}</div></section>}
 {screen==='result'&&current&&<section><div className="eyebrow"><Sparkles size={14}/> TON PROFIL</div><div className="resultCard"><div className="rare">PALM IDENTITY</div><h2 className="profile">{current.profile.name}</h2><div className="tag">{current.profile.tag}</div><p>{current.profile.intro}</p>{['Intuition','Énergie sociale','Adaptabilité'].map((x,i)=><div className="metric" key={x}><div><span>{x}</span><strong>{current.scores[i]}%</strong></div><i><b style={{width:current.scores[i]+'%'}}></b></i></div>)}<div className="power"><span>APERÇU</span><b>{current.profile.power}</b></div></div>{!unlocked?<><div className="premiumPromise"><span>PORTRAIT COMPLET</span><h3>12 chapitres sur ta personnalité</h3><p>Ce que les autres voient de toi, ton fonctionnement mental et émotionnel, tes relations, tes réactions sous pression, ton paradoxe personnel, ton angle mort et ton potentiel. PDF inclus.</p></div><button className="primary" onClick={unlock}><LockKeyhole/> DÉBLOQUER MON PORTRAIT — 2,49 €</button></>:<button className="primary" onClick={()=>setScreen('report')}><Sparkles/> LIRE MON PORTRAIT COMPLET</button>}<button className="secondary"><Share2 size={18}/> Partager mon profil</button><button className="textBtn" onClick={startCamera}>Scanner une autre main</button></section>}
 {screen==='report'&&current&&<section className="fullReport"><div className="reportHero"><div className="eyebrow">PALM PERSONALITY PORTRAIT</div><h2>{current.profile.name}</h2><p>{current.profile.tag}</p><div className="reportMeta"><span>12 chapitres</span><span>Portrait #{String(current.seed).slice(-6)}</span></div></div><div className="reportDisclaimer">Lecture ludique et introspective. PALM n’est pas une évaluation scientifique ou psychologique.</div><div className="longReport">{longReport.map(s=><article key={s.n}><div className="chapterNo">{s.n}</div><div><span>{s.subtitle}</span><h3>{s.title}</h3><p>{s.text}</p></div></article>)}</div><button className="primary" onClick={()=>downloadPalmPDF(current)}><FileDown/> TÉLÉCHARGER MON PORTRAIT PDF</button><button className="secondary" onClick={compare}><Heart size={18}/> Tester une compatibilité</button><button className="secondary" onClick={openHistory}>Mes profils</button></section>}
 {screen==='history'&&<section><div className="eyebrow"><History size={14}/> HISTORIQUE</div><h2>Mes profils</h2><p>{history.length?`${history.length} profil${history.length>1?'s':''} enregistré${history.length>1?'s':''}.`:'Aucun profil enregistré pour le moment.'}</p><div className="historyList">{history.map((h,i)=><button key={h.id+i} className="historyCard" onClick={()=>{setCurrent(h);setScreen('result')}}><div className="avatar">{h.profile.name.split(' ')[1][0]}</div><div><b>{h.name}</b><span>{h.profile.name}</span></div><ChevronRight size={18}/></button>)}</div><button className="primary" onClick={startCamera}><Camera/> NOUVEAU SCAN</button>{history.length>=2&&<button className="secondary" onClick={compare}><Heart size={18}/> Comparer les 2 derniers</button>}</section>}
 {screen==='compat'&&<section><div className="eyebrow"><Heart size={14}/> COMPATIBILITÉ</div><h2>Votre connexion</h2>{pair.length<2?<><p>Il faut au moins 2 profils pour calculer une compatibilité.</p><button className="primary" onClick={startCamera}><Camera/> SCANNER UNE AUTRE MAIN</button></>:<div className="resultCard compatibility"><div className="pair"><div><div className="avatar big">{pair[0].profile.name.split(' ')[1][0]}</div><b>{pair[0].profile.name.replace('THE ','')}</b></div><Heart className="heartIcon"/><div><div className="avatar big">{pair[1].profile.name.split(' ')[1][0]}</div><b>{pair[1].profile.name.replace('THE ','')}</b></div></div><div className="compatScore">{compat}%</div><h3>{compat>90?'Duo magnétique':compat>83?'Connexion naturelle':compat>76?'Belle complémentarité':'Duo contrasté'}</h3><p>Vos profils créent une dynamique unique : vos forces peuvent se compléter et vos différences rendre la relation plus stimulante.</p></div>}<button className="secondary" onClick={openHistory}>Retour aux profils</button></section>}
 </main>}
createRoot(document.getElementById('root')).render(<App/>);