import { jsPDF } from 'jspdf';
import './report.css';

const cores={
THE_EXPLORER:{opening:"Tu supportes mal la sensation d'être enfermé dans une seule manière de faire. Tu as besoin de sentir qu'il existe encore une porte, une option ou quelque chose à découvrir.",outside:"On peut te croire très spontané et détaché. En réalité, tu observes beaucoup plus que tu ne le montres et tu sélectionnes vite ce qui mérite vraiment ton énergie.",emotion:"Tu récupères souvent mieux en changeant d'air ou de perspective qu'en restant longtemps à analyser ce que tu ressens.",pressure:"Sous pression, ton premier réflexe peut être de chercher une sortie, une autre idée ou un nouveau terrain plutôt que de rester coincé dans une situation qui t'épuise.",need:"Tu as profondément besoin de liberté, mais pas d'absence de direction. Tu fonctionnes mieux lorsqu'un cap existe sans que chaque étape soit imposée."},
THE_STRATEGIST:{opening:"Tu as rarement besoin qu'on te répète longtemps une situation pour commencer à en voir la logique. Ton esprit cherche spontanément ce qui se passe derrière ce qui est visible.",outside:"Tu peux donner une impression de calme, voire de distance, alors qu'une grande quantité d'informations est en train d'être traitée intérieurement.",emotion:"Tu as tendance à vouloir comprendre ce que tu ressens. Mettre de l'ordre dans une émotion peut te rassurer, mais certaines choses ont besoin d'être vécues avant d'être expliquées.",pressure:"Sous pression, tu peux augmenter encore ton niveau d'analyse. Cela te protège des décisions impulsives, mais peut aussi créer une boucle où tu cherches une certitude impossible.",need:"Tu as besoin de cohérence. Tu acceptes beaucoup de choses lorsqu'elles ont du sens, mais tu supportes difficilement l'arbitraire ou les contradictions répétées."},
THE_CONNECTOR:{opening:"Tu remarques vite ce qui se passe entre les personnes : un changement de ton, une distance inhabituelle, quelqu'un qui se ferme ou au contraire cherche à se rapprocher.",outside:"On peut te percevoir comme naturellement sociable ou facile à approcher. Ce qu'on voit moins, c'est la quantité d'informations humaines que tu absorbes pendant une interaction.",emotion:"Les émotions des autres peuvent influencer ton propre état plus vite que tu ne le réalises. Tu peux parfois avoir besoin de distance simplement pour savoir ce qui t'appartient vraiment.",pressure:"Sous tension, tu peux chercher à réparer l'ambiance avant de t'occuper de toi. Tu préfères souvent rétablir le lien plutôt que laisser une relation dans une zone floue.",need:"Tu as besoin de liens sincères et réciproques. Être entouré ne suffit pas : tu fonctionnes mieux quand tu sens qu'il existe une vraie qualité de connexion."},
THE_CREATOR:{opening:"Ton esprit ne suit pas toujours la route la plus courte. Une idée en déclenche une autre, puis une association inattendue apparaît et tu vois soudain une possibilité que personne n'avait formulée.",outside:"On peut te trouver original, imprévisible ou difficile à ranger dans une case. En réalité, tu cherches surtout une manière de faire qui te ressemble vraiment.",emotion:"Tu peux transformer ce que tu ressens en idée, humour, esthétique ou projet. Créer est parfois pour toi une manière indirecte de mettre de l'ordre dans ce qui se passe à l'intérieur.",pressure:"Sous pression, ton imagination peut soit devenir extrêmement productive, soit partir dans trop de directions. Le cadre que tu rejettes parfois est précisément ce qui peut alors t'aider.",need:"Tu as besoin d'expression et d'espace mental. Répéter longtemps quelque chose qui n'a plus de sens pour toi peut vider très vite ton énergie."},
THE_LEADER:{opening:"Lorsque personne ne décide, tu ressens vite le vide. Même si tu ne cherches pas systématiquement à diriger, tu as tendance à préférer une direction imparfaite à une attente interminable.",outside:"On peut te percevoir comme très sûr de toi. Ce qu'on voit moins, c'est que ta confiance vient souvent du fait que tu acceptes de décider sans avoir toutes les garanties.",emotion:"Tu peux avoir tendance à agir sur une émotion plutôt qu'à rester longtemps dedans. Faire quelque chose te redonne plus facilement une sensation de contrôle.",pressure:"Sous pression, tu accélères. Tu peux devenir plus direct, plus exigeant et moins patient avec les hésitations, y compris les tiennes.",need:"Tu as besoin de sentir que tu peux avoir un impact réel. Les environnements où tout est lent, flou ou impossible à influencer finissent rapidement par te frustrer."},
THE_GUARDIAN:{opening:"Tu accordes plus de valeur à la fiabilité qu'aux grands effets. Lorsqu'une personne compte pour toi, ta manière de le montrer passe souvent par ce que tu fais régulièrement plutôt que par ce que tu annonces.",outside:"On peut te voir comme stable et solide. Ce qu'on remarque moins, c'est que cette stabilité te demande parfois de contenir beaucoup de choses pour ne pas perturber les autres.",emotion:"Tu ne donnes pas nécessairement accès immédiatement à tout ce que tu ressens. La confiance précède souvent la vulnérabilité chez toi.",pressure:"Sous pression, tu peux t'accrocher davantage à ce que tu connais et prendre encore plus de responsabilités, parfois alors que tu aurais justement besoin d'en déposer.",need:"Tu as besoin de confiance et de continuité. L'imprévisibilité n'est pas forcément un problème lorsqu'elle repose sur une relation suffisamment sûre."}
};
const keyOf=n=>n.replaceAll(' ','_');
const level=n=>n>=88?'très élevé':n>=80?'élevé':n>=72?'marqué':'modéré';
const pick=(seed,arr,offset=0)=>arr[(seed+offset)%arr.length];
function dynamic(current){const[a,b,c]=current.scores,s=current.seed||1;return{
intuition:a>=84?"Tu fais souvent confiance à une impression avant de pouvoir l'expliquer. Le détail intéressant, c'est que tu peux ensuite reconstruire rationnellement les raisons de ce choix, comme si ton intuition avait quelques secondes d'avance sur ton raisonnement.":"Tu alternes intuition et vérification. Une première impression compte, mais tu sembles avoir besoin d'un élément supplémentaire avant de lui donner complètement raison.",
social:b>=85?"Ton énergie sociale est visible : une interaction peut t'activer plutôt que te fatiguer, surtout lorsque tu sens que le courant passe. Cela ne veut pas dire que tu veux toujours être entouré ; tu peux aussi devenir très sélectif sur les personnes auxquelles tu donnes réellement accès.":b>=76?"Tu n'as pas besoin d'être constamment au centre pour exister dans un groupe. Tu peux passer de très présent à beaucoup plus observateur selon les personnes et l'ambiance.":"Tu sembles sélectionner fortement tes interactions. Tu peux être très ouvert avec quelques personnes et étonnamment réservé dès que le contexte te paraît superficiel ou forcé.",
adapt:c>=86?"Tu changes rapidement de stratégie lorsqu'un contexte évolue. Cette souplesse est une force, mais elle peut donner aux autres l'impression que tu as changé d'avis alors que, de ton point de vue, tu as simplement intégré une nouvelle information.":"Tu sais t'adapter, mais pas au prix de tout. Lorsque quelque chose touche à une valeur importante pour toi, ta souplesse diminue nettement et tu peux devenir beaucoup plus ferme qu'on ne l'attendait.",
paradox:pick(s,["Tu peux aimer la nouveauté tout en ayant besoin de quelques repères très stables. Ce n'est pas contradictoire : la sécurité sur certains points te permet justement d'être plus libre sur les autres.","Tu peux paraître sûr de toi dans une situation et beaucoup plus sensible au regard des autres dans une autre. Ta confiance dépend moins d'une confiance générale que du sentiment de maîtriser le terrain.","Tu apprécies l'autonomie, mais certaines relations prennent chez toi une place très forte. Tu peux donc réclamer de l'espace tout en étant profondément attaché.","Tu peux être très rationnel pour les problèmes des autres et beaucoup plus intuitif lorsqu'une décision te concerne personnellement."],3),
blind:pick(s,["Tu peux sous-estimer l'effet que ton humeur ou ton niveau d'engagement produit sur les autres. Quand tu décroches intérieurement, cela peut être visible avant même que tu le dises.","Parce que certaines choses te semblent évidentes, tu peux oublier qu'elles ne le sont pas pour les autres. Expliquer davantage ton raisonnement éviterait parfois des malentendus.","Tu peux continuer à fonctionner correctement alors que ton énergie est déjà basse. Le risque est de remarquer tardivement que tu avais besoin d'une vraie coupure.","Tu peux confondre parfois ce que tu sais faire facilement avec quelque chose de banal. Une partie de ton potentiel se trouve précisément dans les capacités que tu ne penses pas devoir valoriser."],7)} }
export function buildLongReport(current){const p=current.profile,k=keyOf(p.name),v=cores[k]||cores.THE_EXPLORER,d=dynamic(current),[a,b,c]=current.scores;return[
{n:'01',title:'Qui tu es vraiment',subtitle:'Ta signature dominante',text:`${v.opening} ${d.paradox}`},
{n:'02',title:'Ce que les autres voient de toi',subtitle:'Image extérieure vs fonctionnement intérieur',text:`${v.outside} ${d.social}`},
{n:'03',title:'Comment ton esprit fonctionne',subtitle:`Intuition ${a}% — niveau ${level(a)}`,text:`${d.intuition} Tu sembles fonctionner particulièrement bien lorsque tu peux d'abord saisir l'ensemble, puis revenir sur les détails qui comptent réellement.`},
{n:'04',title:'Ta façon d’agir',subtitle:`Adaptabilité ${c}% — niveau ${level(c)}`,text:`${d.adapt} Dans l'action, tu sembles préférer conserver une marge de manœuvre plutôt que suivre aveuglément une méthode qui ne correspond plus à la situation.`},
{n:'05',title:'Ton fonctionnement émotionnel',subtitle:'Ce que tu montres — et ce que tu gardes',text:`${v.emotion} Tu n'exprimes donc pas nécessairement une émotion au même moment que tu la ressens : ton contexte et ton niveau de confiance changent beaucoup la manière dont elle devient visible.`},
{n:'06',title:'Ta personnalité sociale',subtitle:`Énergie sociale ${b}% — niveau ${level(b)}`,text:`${d.social} Ce qui compte chez toi semble moins être le nombre de personnes présentes que la qualité du signal que tu reçois du groupe : intérêt, confiance, liberté ou stimulation.`},
{n:'07',title:'Dans tes relations proches',subtitle:'Attachement, confiance et attentes',text:`${v.need} Une fois la confiance installée, tu peux donner beaucoup. En revanche, tu réagis particulièrement aux situations où tu as l'impression que la réciprocité ou la cohérence disparaît.`},
{n:'08',title:'Quand tu es sous pression',subtitle:'Ton mode automatique',text:`${v.pressure} C'est souvent ici qu'une qualité naturelle peut devenir excessive : ce qui t'aide habituellement peut se rigidifier lorsque ton niveau de tension monte.`},
{n:'09',title:'Ton paradoxe personnel',subtitle:'Deux facettes qui coexistent',text:`${d.paradox} C'est probablement l'une des raisons pour lesquelles certaines personnes peuvent avoir de toi des descriptions assez différentes tout en ayant toutes, en partie, raison.`},
{n:'10',title:'Ce dont tu as profondément besoin',subtitle:'Ton environnement idéal',text:`${v.need} Lorsque ces conditions sont présentes, ton profil ${p.name.replace('THE ','').toLowerCase()} exprime davantage ses qualités naturelles : ${p.strength.toLowerCase()}, capacité d'adaptation et sentiment d'agir de façon authentique.`},
{n:'11',title:'Ton angle mort',subtitle:'Ce que tu pourrais ne pas voir chez toi',text:`${d.blind} Ce n'est pas une faiblesse fixe : c'est simplement un endroit où davantage de conscience peut changer rapidement ta manière de fonctionner.`},
{n:'12',title:'Ton potentiel',subtitle:p.potential,text:`${p.potential} Ton axe n'est pas de devenir quelqu'un d'autre, mais de savoir quand utiliser ta stratégie naturelle et quand en choisir une différente. ${p.growth}`}
]}
export function downloadPalmPDF(current){const report=buildLongReport(current),doc=new jsPDF({unit:'mm',format:'a4'});let y=22;const add=()=>{doc.addPage();y=22};doc.setFillColor(12,12,14);doc.rect(0,0,210,297,'F');doc.setTextColor(245,242,235);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('PALM / PERSONALITY PORTRAIT',18,22);doc.setFontSize(29);doc.text(current.profile.name,18,49);doc.setFont('helvetica','normal');doc.setFontSize(12);doc.setTextColor(174,170,163);doc.text(current.profile.tag,18,59);doc.setDrawColor(80,78,72);doc.line(18,70,192,70);doc.setTextColor(230,226,218);doc.setFontSize(12.5);doc.text(doc.splitTextToSize('Ton portrait personnel explore ton fonctionnement, tes relations, tes réactions sous pression, tes paradoxes et ton potentiel.',166),18,86);doc.setFontSize(9);doc.setTextColor(130,128,123);doc.text('Lecture ludique et introspective — ne constitue pas une évaluation psychologique ou scientifique.',18,274);add();report.forEach(s=>{const lines=doc.splitTextToSize(s.text,160),need=31+lines.length*5;if(y+need>274)add();doc.setTextColor(140,136,128);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(s.n,18,y);doc.setTextColor(24,24,25);doc.setFontSize(17);doc.text(s.title,30,y);y+=9;doc.setTextColor(100,96,90);doc.setFontSize(9.5);doc.text(s.subtitle,30,y);y+=8;doc.setTextColor(45,43,40);doc.setFont('helvetica','normal');doc.setFontSize(10.5);doc.text(lines,30,y);y+=lines.length*5+13});const pages=doc.getNumberOfPages();for(let i=2;i<=pages;i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(150,147,141);doc.text(`PALM • ${current.profile.name}`,18,287);doc.text(`${i}/${pages}`,188,287,{align:'right'})}doc.save(`PALM-${current.profile.name.replaceAll(' ','-')}.pdf`)}