import React,{useMemo,useState}from'react';
import{Users,Heart,Camera,ChevronRight,Sparkles,Check,X}from'lucide-react';
import{buildCompatibility,shareCompatibility,downloadShareCard}from'./social.js';

const first=n=>n?.replace(/^Profil\s+/,'Ami ')||'Profil';
export default function SocialHub({history,onScan,onOpen,onRename,onDelete}){
 const[mode,setMode]=useState('hub'),[selected,setSelected]=useState([]);
 const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const people=history.filter(h=>selected.includes(h.id));
 const match=mode==='matchResult'&&people.length===2?buildCompatibility(people[0],people[1]):null;
 const group=useMemo(()=>{if(people.length<3)return null;const pairs=[];for(let i=0;i<people.length;i++)for(let j=i+1;j<people.length;j++){const c=buildCompatibility(people[i],people[j]);pairs.push({a:people[i],b:people[j],c})}pairs.sort((a,b)=>b.c.score-a.c.score);const avg=Math.round(pairs.reduce((s,p)=>s+p.c.score,0)/pairs.length);const leader=[...people].sort((a,b)=>b.scores[1]-a.scores[1])[0],connector=[...people].sort((a,b)=>b.scores[0]-a.scores[0])[0],wild=[...people].sort((a,b)=>b.scores[2]-a.scores[2])[0];return{pairs,avg,leader,connector,wild}},[people]);
 const picker=(title,sub,min,max,next)=><><button className="backLink" onClick={()=>{setMode('hub');setSelected([])}}>← Retour</button><div className="eyebrow"><Users size={14}/> PALM SOCIAL</div><h2>{title}</h2><p>{sub}</p><div className="peoplePicker">{history.map(h=>{const active=selected.includes(h.id);return <button key={h.id} className={'personPick '+(active?'selected':'')} onClick={()=>{if(!active&&selected.length>=max)return;toggle(h.id)}}><div className="avatar">{(h.name||'P')[0].toUpperCase()}</div><div><b>{first(h.name)}</b><span>{h.profile.name}</span></div><i>{active?<Check size={16}/>:<span/>}</i></button>})}</div>{history.length<min&&<div className="emptySocial"><p>Il manque {min-history.length} profil{min-history.length>1?'s':''}.</p><button className="secondary" onClick={onScan}><Camera/> Scanner quelqu’un</button></div>}<button className="primary" disabled={selected.length<min} onClick={()=>setMode(next)}>{selected.length<min?`Choisis ${min} personne${min>1?'s':''}`:next==='matchResult'?'RÉVÉLER LE MATCH':'ANALYSER LE GROUPE'} <ChevronRight/></button></>;
 if(mode==='match')return <section>{picker('Qui veux-tu matcher ?','Choisis exactement 2 personnes. PALM compare leurs profils et révèle leur dynamique.',2,2,'matchResult')}</section>;
 if(mode==='group')return <section>{picker('Qui est dans le groupe ?','Choisis de 3 à 6 personnes pour révéler les rôles, les affinités et la dynamique du groupe.',3,6,'groupResult')}</section>;
 if(mode==='matchResult'&&match)return <section className="socialReport"><button className="backLink" onClick={()=>setMode('match')}>← Changer les personnes</button><div className="eyebrow"><Heart size={14}/> VOTRE MATCH</div><div className="matchHero"><span>{match.label}</span><div className="compatScore">{match.score}%</div><h2>{first(people[0].name)} × {first(people[1].name)}</h2><p>{match.hook}</p></div><div className="matchChapters">{match.chapters.map((c,i)=><article key={c.title}><b>0{i+1}</b><div><h3>{c.title}</h3><p>{c.text}</p></div></article>)}</div><button className="primary" onClick={()=>shareCompatibility(people[0],people[1],match)}><Heart/> PARTAGER LE MATCH</button><button className="secondary" onClick={()=>downloadShareCard(people[0],people[1],match)}>Partager la carte</button></section>;
 if(mode==='groupResult'&&group)return <section><button className="backLink" onClick={()=>setMode('group')}>← Modifier le groupe</button><div className="eyebrow"><Users size={14}/> GROUP VIBE</div><h2>Votre groupe</h2><div className="groupScore"><span>ALCHIMIE DU GROUPE</span><strong>{group.avg}%</strong><p>{group.avg>=86?'Une équipe très connectée, avec une vraie énergie collective.':group.avg>=78?'Un groupe équilibré : assez de ressemblances pour connecter, assez de différences pour créer du mouvement.':'Un groupe contrasté où les personnalités peuvent beaucoup s’apporter.'}</p></div><div className="groupRoles"><div><span>⚡ DONNE LE TEMPO</span><b>{first(group.leader.name)}</b></div><div><span>🧲 CONNECTE LE GROUPE</span><b>{first(group.connector.name)}</b></div><div><span>✨ SURPREND LE PLUS</span><b>{first(group.wild.name)}</b></div></div><h3 className="sectionTitle">Les connexions du groupe</h3>{group.pairs.map((p,i)=><div className="pairRow" key={p.a.id+'-'+p.b.id}><div><b>{first(p.a.name)} × {first(p.b.name)}</b><span>{p.c.label}</span></div><strong>{p.c.score}%</strong></div>)}<button className="primary" onClick={onScan}><Camera/> AJOUTER QUELQU’UN</button></section>;
 return <section><div className="eyebrow"><Users size={14}/> PALM SOCIAL</div><h2>À plusieurs, c’est mieux.</h2><p>Choisis ce que tu veux découvrir. Tu peux matcher deux personnes ou analyser tout ton groupe.</p><div className="socialChoices"><button onClick={()=>{setSelected([]);setMode('match')}}><Heart/><div><b>Match</b><span>Compare 2 personnes</span><p>Compatibilité, forces du duo, points de friction.</p></div><ChevronRight/></button><button onClick={()=>{setSelected([]);setMode('group')}}><Users/><div><b>Groupe</b><span>Analyse 3 à 6 amis</span><p>Rôles, alchimie et meilleurs duos du groupe.</p></div><ChevronRight/></button></div><div className="socialProfiles"><div className="socialProfilesHead"><b>Mes personnes</b><span>{history.length} profil{history.length!==1?'s':''}</span></div>{history.map(h=><div className="miniPerson" key={h.id}><button onClick={()=>onOpen(h)}><div className="avatar">{(h.name||'P')[0].toUpperCase()}</div><div><b>{first(h.name)}</b><span>{h.profile.name}</span></div></button><div><button onClick={()=>onRename(h)}>Nom</button><button className="dangerMini" onClick={()=>onDelete(h)}><X size={13}/></button></div></div>)}<button className="addPerson" onClick={onScan}><Camera size={17}/> Scanner quelqu’un</button></div></section>;
}