import React,{useMemo,useState}from'react';
import{Users,Heart,Camera,ChevronRight,Check,X,LockKeyhole}from'lucide-react';
import{buildCompatibility,shareCompatibility,downloadShareCard}from'./social.js';
const first=n=>n?.replace(/^Profil\s+/,'Ami ')||'Profil';
export default function SocialHub({history,onScan,onOpen,onRename,onDelete,unlocked=false,onUnlock}){
 const[mode,setMode]=useState('hub'),[selected,setSelected]=useState([]);const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const people=history.filter(h=>selected.includes(h.id));const match=mode==='matchResult'&&people.length===2?buildCompatibility(people[0],people[1]):null;
 const group=useMemo(()=>{if(people.length<3)return null;const pairs=[];for(let i=0;i<people.length;i++)for(let j=i+1;j<people.length;j++){const c=buildCompatibility(people[i],people[j]);pairs.push({a:people[i],b:people[j],c})}pairs.sort((a,b)=>b.c.score-a.c.score);const avg=Math.round(pairs.reduce((s,p)=>s+p.c.score,0)/pairs.length);return{pairs,avg,leader:[...people].sort((a,b)=>b.scores[1]-a.scores[1])[0],connector:[...people].sort((a,b)=>b.scores[0]-a.scores[0])[0],wild:[...people].sort((a,b)=>b.scores[2]-a.scores[2])[0]}},[people]);
 const paywall=(title,copy)=><div className="socialPaywall"><LockKeyhole/><span>PALM UNLIMITED</span><h3>{title}</h3><p>{copy}</p><button className="primary" onClick={onUnlock}>DÉBLOQUER TOUT — 1,99 €</button><small>Paiement unique • accès illimité</small></div>;
 const picker=(title,sub,min,max,next)=><><button className="backLink" onClick={()=>{setMode('hub');setSelected([])}}>← Retour</button><div className="eyebrow"><Users size={14}/> PALM SOCIAL</div><h2>{title}</h2><p>{sub}</p><div className="peoplePicker">{history.map(h=>{const active=selected.includes(h.id);return <button key={h.id} className={'personPick '+(active?'selected':'')} onClick={()=>{if(!active&&selected.length>=max)return;toggle(h.id)}}><div className="avatar">{(h.name||'P')[0].toUpperCase()}</div><div><b>{first(h.name)}</b><span>{h.profile.name}</span></div><i>{active?<Check size={16}/>:<span/>}</i></button>})}</div>{history.length<min&&<div className="emptySocial"><p>Il manque {min-history.length} profil{min-history.length>1?'s':''}.</p><button className="secondary" onClick={onScan}><Camera/> Scanner quelqu’un</button></div>}<button className="primary" disabled={selected.length<min} onClick={()=>setMode(next)}>{selected.length<min?`Choisis ${min} personne${min>1?'s':''}`:next==='matchResult'?'RÉVÉLER LE MATCH':'ANALYSER LE GROUPE'} <ChevronRight/></button></>;
 if(mode==='match')return <section>{picker('Qui veux-tu matcher ?','Choisis 2 personnes. Le score est gratuit ; PALM Unlimited révèle toute la dynamique du duo.',2,2,'matchResult')}</section>;
 if(mode==='group')return <section>{unlocked?picker('Qui est dans le groupe ?','Choisis de 3 à 6 personnes pour révéler les rôles, les affinités et la dynamique du groupe.',3,6,'groupResult'):<><button className="backLink" onClick={()=>setMode('hub')}>← Retour</button><div className="eyebrow"><Users size={14}/> GROUPE</div><h2>Ta bande a une personnalité.</h2><p>PALM analyse 3 à 6 personnes pour révéler l’alchimie du groupe, les rôles naturels et les meilleurs duos.</p>{paywall('Débloque le mode Groupe','Crée autant de groupes que tu veux et découvre qui donne le tempo, qui connecte la bande et quels duos ont le plus d’alchimie.')}</>};
 if(mode==='matchResult'&&match)return <section className="socialReport"><button className="backLink" onClick={()=>setMode('match')}>← Changer les personnes</button><div className="eyebrow"><Heart size={14}/> VOTRE MATCH</div><div className="matchHero"><span>{match.label}</span><div className="compatScore">{match.score}%</div><h2>{first(people[0].name)} × {first(people[1].name)}</h2><p>{match.hook}</p></div>{unlocked?<><div className="matchChapters">{match.chapters.map((c,i)=><article key={c.title}><b>0{i+1}</b><div><h3>{c.title}</h3><p>{c.text}</p></div></article>)}</div><button className="primary" onClick={()=>shareCompatibility(people[0],people[1],match)}><Heart/> PARTAGER LE MATCH</button><button className="secondary" onClick={()=>downloadShareCard(people[0],people[1],match)}>Partager la carte</button></>:<><div className="lockedPreview"><div><LockKeyhole/><span>Pourquoi ça fonctionne</span></div><div><LockKeyhole/><span>Votre point de friction</span></div><div><LockKeyhole/><span>Votre superpouvoir de duo</span></div></div>{paywall('Tu connais le score. Découvre pourquoi.','Débloque le rapport complet de votre match, les cartes à partager, les groupes et les scans illimités.')}</>}</section>;
 if(mode==='groupResult'&&group)return <section><button className="backLink" onClick={()=>setMode('group')}>← Modifier le groupe</button><div className="eyebrow"><Users size={14}/> GROUP VIBE</div><h2>Votre groupe</h2><div className="groupScore"><span>ALCHIMIE DU GROUPE</span><strong>{group.avg}%</strong></div><div className="groupRoles"><div><span>⚡ DONNE LE TEMPO</span><b>{first(group.leader.name)}</b></div><div><span>🧲 CONNECTE LE GROUPE</span><b>{first(group.connector.name)}</b></div><div><span>✨ SURPREND LE PLUS</span><b>{first(group.wild.name)}</b></div></div></section>;
 return <section><div className="eyebrow"><Users size={14}/> PALM SOCIAL</div><h2>Et maintenant, joue avec les autres.</h2><p>Ton profil n’est que le début. Compare-toi à quelqu’un gratuitement, puis débloque toute l’expérience PALM.</p><div className="socialChoices"><button onClick={()=>{setSelected([]);setMode('match')}}><Heart/><div><b>Match</b><span>Score de compatibilité gratuit</span><p>Choisis 2 personnes et découvre immédiatement votre %.</p></div><ChevronRight/></button><button onClick={()=>{setSelected([]);setMode('group')}}><Users/><div><b>Groupe {unlocked?'':'🔒'}</b><span>3 à 6 amis</span><p>Alchimie, rôles et meilleurs duos de la bande.</p></div><ChevronRight/></button></div><div className="socialProfiles"><div className="socialProfilesHead"><b>Mes personnes</b><span>{history.length} profil{history.length!==1?'s':''}</span></div>{history.map(h=><div className="miniPerson" key={h.id}><button onClick={()=>onOpen(h)}><div className="avatar">{(h.name||'P')[0].toUpperCase()}</div><div><b>{first(h.name)}</b><span>{h.profile.name}</span></div></button><div><button onClick={()=>onRename(h)}>Nom</button><button className="dangerMini" onClick={()=>onDelete(h)}><X size={13}/></button></div></div>)}<button className="addPerson" onClick={onScan}><Camera size={17}/> Scanner quelqu’un</button></div></section>;
}